exports.currencyList = [
  {
    currency_symbol: '$',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'US Dollar',
    currency_code: 'USD',
    enabled: true,
  },
  {
    currency_symbol: '€',
    currency_position: 'after',
    decimal_sep: '.',
    thousand_sep: ' ',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'Euro',
    currency_code: 'EUR',
    enabled: true,
  },
  {
    currency_symbol: '£',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'British Pound',
    currency_code: 'GBP',
    enabled: true,
  },
  {
    currency_symbol: '¥',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 0,
    zero_format: false,
    currency_name: 'Japanese Yen',
    currency_code: 'JPY',
    enabled: true,
  },
  {
    currency_symbol: '₹',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'Indian Rupee',
    currency_code: 'INR',
    enabled: true,
  },
  {
    currency_symbol: 'C$',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'Canadian Dollar',
    currency_code: 'CAD',
    enabled: true,
  },
  {
    currency_symbol: 'A$',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: false,
    currency_name: 'Australian Dollar',
    currency_code: 'AUD',
    enabled: true,
  },
  {
    currency_symbol: 'CHF',
    currency_position: 'after',
    decimal_sep: '.',
    thousand_sep: "'",
    cent_precision: 2,
    zero_format: false,
    currency_name: 'Swiss Franc',
    currency_code: 'CHF',
    enabled: true,
  },
];
