const currencyData = [
  { currency_code: 'USD', flag: '🇺🇸', symbol: '$', name: 'US Dollar' },
  { currency_code: 'CAD', flag: '🇨🇦', symbol: 'C$', name: 'Canadian Dollar' },
  { currency_code: 'EUR', flag: '🇪🇺', symbol: '€', name: 'Euro' },
  { currency_code: 'AED', flag: '🇦🇪', symbol: 'د.إ', name: 'UAE Dirham' },
  { currency_code: 'AFN', flag: '🇦🇫', symbol: '؋', name: 'Afghan Afghani' },
  { currency_code: 'ALL', flag: '🇦🇱', symbol: 'L', name: 'Albanian Lek' },
  { currency_code: 'AMD', flag: '🇦🇲', symbol: '֏', name: 'Armenian Dram' },
  { currency_code: 'ARS', flag: '🇦🇷', symbol: '$', name: 'Argentine Peso' },
  { currency_code: 'AUD', flag: '🇦🇺', symbol: 'A$', name: 'Australian Dollar' },
  { currency_code: 'AZN', flag: '🇦🇿', symbol: '₼', name: 'Azerbaijani Manat' },
  { currency_code: 'BAM', flag: '🇧🇦', symbol: 'КМ', name: 'Bosnia-Herzegovina Mark' },
  { currency_code: 'BDT', flag: '🇧🇩', symbol: '৳', name: 'Bangladeshi Taka' },
  { currency_code: 'BGN', flag: '🇧🇬', symbol: 'лв', name: 'Bulgarian Lev' },
  { currency_code: 'BHD', flag: '🇧🇭', symbol: 'د.ب', name: 'Bahraini Dinar' },
  { currency_code: 'BIF', flag: '🇧🇮', symbol: 'FBu', name: 'Burundian Franc' },
  { currency_code: 'BND', flag: '🇧🇳', symbol: 'B$', name: 'Brunei Dollar' },
  { currency_code: 'BOB', flag: '🇧🇴', symbol: 'Bs', name: 'Bolivian Boliviano' },
  { currency_code: 'BRL', flag: '🇧🇷', symbol: 'R$', name: 'Brazilian Real' },
  { currency_code: 'BWP', flag: '🇧🇼', symbol: 'P', name: 'Botswana Pula' },
  { currency_code: 'BYR', flag: '🇧🇾', symbol: 'Br', name: 'Belarusian Ruble' },
  { currency_code: 'BZD', flag: '🇧🇿', symbol: 'BZ$', name: 'Belize Dollar' },
  { currency_code: 'CDF', flag: '🇨🇩', symbol: 'FC', name: 'Congolese Franc' },
  { currency_code: 'CHF', flag: '🇨🇭', symbol: 'CHF', name: 'Swiss Franc' },
  { currency_code: 'CLP', flag: '🇨🇱', symbol: '$', name: 'Chilean Peso' },
  { currency_code: 'CNY', flag: '🇨🇳', symbol: '¥', name: 'Chinese Yuan' },
  { currency_code: 'COP', flag: '🇨🇴', symbol: '$', name: 'Colombian Peso' },
  { currency_code: 'CRC', flag: '🇨🇷', symbol: '₡', name: 'Costa Rican Colón' },
  { currency_code: 'CVE', flag: '🇨🇻', symbol: '$', name: 'Cape Verdean Escudo' },
  { currency_code: 'CZK', flag: '🇨🇿', symbol: 'Kč', name: 'Czech Koruna' },
  { currency_code: 'DJF', flag: '🇩🇯', symbol: 'Fdj', name: 'Djiboutian Franc' },
  { currency_code: 'DKK', flag: '🇩🇰', symbol: 'kr', name: 'Danish Krone' },
  { currency_code: 'DOP', flag: '🇩🇴', symbol: 'RD$', name: 'Dominican Peso' },
  { currency_code: 'DZD', flag: '🇩🇿', symbol: 'د.ج', name: 'Algerian Dinar' },
  { currency_code: 'EEK', flag: '🇪🇪', symbol: 'kr', name: 'Estonian Kroon' },
  { currency_code: 'EGP', flag: '🇪🇬', symbol: '£', name: 'Egyptian Pound' },
  { currency_code: 'ERN', flag: '🇪🇷', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { currency_code: 'ETB', flag: '🇪🇹', symbol: 'Br', name: 'Ethiopian Birr' },
  { currency_code: 'GBP', flag: '🇬🇧', symbol: '£', name: 'British Pound' },
  { currency_code: 'GEL', flag: '🇬🇪', symbol: '₾', name: 'Georgian Lari' },
  { currency_code: 'GHS', flag: '🇬🇭', symbol: '₵', name: 'Ghanaian Cedi' },
  { currency_code: 'GNF', flag: '🇬🇳', symbol: 'FG', name: 'Guinean Franc' },
  { currency_code: 'GTQ', flag: '🇬🇹', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { currency_code: 'HKD', flag: '🇭🇰', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { currency_code: 'HNL', flag: '🇭🇳', symbol: 'L', name: 'Honduran Lempira' },
  { currency_code: 'HRK', flag: '🇭🇷', symbol: 'kn', name: 'Croatian Kuna' },
  { currency_code: 'HUF', flag: '🇭🇺', symbol: 'Ft', name: 'Hungarian Forint' },
  { currency_code: 'IDR', flag: '🇮🇩', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { currency_code: 'ILS', flag: '🇮🇱', symbol: '₪', name: 'Israeli Shekel' },
  { currency_code: 'INR', flag: '🇮🇳', symbol: '₹', name: 'Indian Rupee' },
  { currency_code: 'IQD', flag: '🇮🇶', symbol: 'د.ع', name: 'Iraqi Dinar' },
  { currency_code: 'IRR', flag: '🇮🇷', symbol: '﷼', name: 'Iranian Rial' },
  { currency_code: 'ISK', flag: '🇮🇸', symbol: 'kr', name: 'Icelandic Krona' },
  { currency_code: 'JMD', flag: '🇯🇲', symbol: 'J$', name: 'Jamaican Dollar' },
  { currency_code: 'JOD', flag: '🇯🇴', symbol: 'د.ا', name: 'Jordanian Dinar' },
  { currency_code: 'JPY', flag: '🇯🇵', symbol: '¥', name: 'Japanese Yen' },
  { currency_code: 'KES', flag: '🇰🇪', symbol: 'KSh', name: 'Kenyan Shilling' },
  { currency_code: 'KGS', flag: '🇰🇬', symbol: 'лв', name: 'Kyrgyzstani Som' },
  { currency_code: 'KHR', flag: '🇰🇭', symbol: '៛', name: 'Cambodian Riel' },
  { currency_code: 'KMF', flag: '🇰🇲', symbol: 'CF', name: 'Comorian Franc' },
  { currency_code: 'KPW', flag: '🇰🇵', symbol: '₩', name: 'North Korean Won' },
  { currency_code: 'KRW', flag: '🇰🇷', symbol: '₩', name: 'South Korean Won' },
  { currency_code: 'KWD', flag: '🇰🇼', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  { currency_code: 'KYD', flag: '🇰🇾', symbol: 'CI$', name: 'Cayman Islands Dollar' },
  { currency_code: 'KZT', flag: '🇰🇿', symbol: '₸', name: 'Kazakhstani Tenge' },
  { currency_code: 'LAK', flag: '🇱🇦', symbol: '₭', name: 'Lao Kip' },
  { currency_code: 'LBP', flag: '🇱🇧', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { currency_code: 'LKR', flag: '🇱🇰', symbol: '₨', name: 'Sri Lankan Rupee' },
  { currency_code: 'LRD', flag: '🇱🇷', symbol: 'L$', name: 'Liberian Dollar' },
  { currency_code: 'LSL', flag: '🇱🇸', symbol: 'L', name: 'Lesotho Loti' },
  { currency_code: 'LTL', flag: '🇱🇹', symbol: 'Lt', name: 'Lithuanian Litas' },
  { currency_code: 'LVL', flag: '🇱🇻', symbol: 'Ls', name: 'Latvian Lats' },
  { currency_code: 'LYD', flag: '🇱🇾', symbol: 'ل.د', name: 'Libyan Dinar' },
  { currency_code: 'MAD', flag: '🇲🇦', symbol: 'د.م.', name: 'Moroccan Dirham' },
  { currency_code: 'MDL', flag: '🇲🇩', symbol: 'L', name: 'Moldovan Leu' },
  { currency_code: 'MGA', flag: '🇲🇬', symbol: 'Ar', name: 'Malagasy Ariary' },
  { currency_code: 'MKD', flag: '🇲🇰', symbol: 'ден', name: 'Macedonian Denar' },
  { currency_code: 'MMK', flag: '🇲🇲', symbol: 'K', name: 'Myanmar Kyat' },
  { currency_code: 'MNT', flag: '🇲🇳', symbol: '₮', name: 'Mongolian Tugrik' },
  { currency_code: 'MOP', flag: '🇲🇴', symbol: 'MOP$', name: 'Macanese Pataca' },
  { currency_code: 'MUR', flag: '🇲🇺', symbol: '₨', name: 'Mauritian Rupee' },
  { currency_code: 'MVR', flag: '🇲🇻', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { currency_code: 'MWK', flag: '🇲🇼', symbol: 'MK', name: 'Malawian Kwacha' },
  { currency_code: 'MXN', flag: '🇲🇽', symbol: '$', name: 'Mexican Peso' },
  { currency_code: 'MYR', flag: '🇲🇾', symbol: 'RM', name: 'Malaysian Ringgit' },
  { currency_code: 'MZN', flag: '🇲🇿', symbol: 'MT', name: 'Mozambican Metical' },
  { currency_code: 'NAD', flag: '🇳🇦', symbol: 'N$', name: 'Namibian Dollar' },
  { currency_code: 'NGN', flag: '🇳🇬', symbol: '₦', name: 'Nigerian Naira' },
  { currency_code: 'NIO', flag: '🇳🇮', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  { currency_code: 'NOK', flag: '🇳🇴', symbol: 'kr', name: 'Norwegian Krone' },
  { currency_code: 'NPR', flag: '🇳🇵', symbol: '₨', name: 'Nepalese Rupee' },
  { currency_code: 'NZD', flag: '🇳🇿', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { currency_code: 'OMR', flag: '🇴🇲', symbol: 'ر.ع.', name: 'Omani Rial' },
  { currency_code: 'PAB', flag: '🇵🇦', symbol: 'B/.', name: 'Panamanian Balboa' },
  { currency_code: 'PEN', flag: '🇵🇪', symbol: 'S/', name: 'Peruvian Sol' },
  { currency_code: 'PGK', flag: '🇵🇬', symbol: 'K', name: 'Papua New Guinean Kina' },
  { currency_code: 'PHP', flag: '🇵🇭', symbol: '₱', name: 'Philippine Peso' },
  { currency_code: 'PKR', flag: '🇵🇰', symbol: '₨', name: 'Pakistani Rupee' },
  { currency_code: 'PLN', flag: '🇵🇱', symbol: 'zł', name: 'Polish Zloty' },
  { currency_code: 'PYG', flag: '🇵🇾', symbol: '₲', name: 'Paraguayan Guarani' },
  { currency_code: 'QAR', flag: '🇶🇦', symbol: 'ر.ق', name: 'Qatari Riyal' },
  { currency_code: 'RON', flag: '🇷🇴', symbol: 'lei', name: 'Romanian Leu' },
  { currency_code: 'RSD', flag: '🇷🇸', symbol: 'дин', name: 'Serbian Dinar' },
  { currency_code: 'RUB', flag: '🇷🇺', symbol: '₽', name: 'Russian Ruble' },
  { currency_code: 'RWF', flag: '🇷🇼', symbol: 'RF', name: 'Rwandan Franc' },
  { currency_code: 'SAR', flag: '🇸🇦', symbol: 'ر.س', name: 'Saudi Riyal' },
  { currency_code: 'SBD', flag: '🇸🇧', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  { currency_code: 'SCR', flag: '🇸🇨', symbol: '₨', name: 'Seychellois Rupee' },
  { currency_code: 'SDG', flag: '🇸🇩', symbol: 'ج.س.', name: 'Sudanese Pound' },
  { currency_code: 'SEK', flag: '🇸🇪', symbol: 'kr', name: 'Swedish Krona' },
  { currency_code: 'SGD', flag: '🇸🇬', symbol: 'S$', name: 'Singapore Dollar' },
  { currency_code: 'SHP', flag: '🇸🇭', symbol: '£', name: 'Saint Helena Pound' },
  { currency_code: 'SLL', flag: '🇸🇱', symbol: 'Le', name: 'Sierra Leonean Leone' },
  { currency_code: 'SOS', flag: '🇸🇴', symbol: 'S', name: 'Somali Shilling' },
  { currency_code: 'SRD', flag: '🇸🇷', symbol: '$', name: 'Surinamese Dollar' },
  { currency_code: 'SSP', flag: '🇸🇸', symbol: '£', name: 'South Sudanese Pound' },
  { currency_code: 'STD', flag: '🇸🇹', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  { currency_code: 'SVC', flag: '🇸🇻', symbol: '$', name: 'Salvadoran Colón' },
  { currency_code: 'SYP', flag: '🇸🇾', symbol: '£', name: 'Syrian Pound' },
  { currency_code: 'SZL', flag: '🇸🇿', symbol: 'L', name: 'Swazi Lilangeni' },
  { currency_code: 'THB', flag: '🇹🇭', symbol: '฿', name: 'Thai Baht' },
  { currency_code: 'TJS', flag: '🇹🇯', symbol: 'SM', name: 'Tajikistani Somoni' },
  { currency_code: 'TMT', flag: '🇹🇲', symbol: 'T', name: 'Turkmenistani Manat' },
  { currency_code: 'TND', flag: '🇹🇳', symbol: 'د.ت', name: 'Tunisian Dinar' },
  { currency_code: 'TOP', flag: '🇹🇴', symbol: 'T$', name: 'Tongan Paʻanga' },
  { currency_code: 'TRY', flag: '🇹🇷', symbol: '₺', name: 'Turkish Lira' },
  { currency_code: 'TTD', flag: '🇹🇹', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  { currency_code: 'TWD', flag: '🇹🇼', symbol: 'NT$', name: 'Taiwan New Dollar' },
  { currency_code: 'TZS', flag: '🇹🇿', symbol: 'TSh', name: 'Tanzanian Shilling' },
  { currency_code: 'UAH', flag: '🇺🇦', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { currency_code: 'UGX', flag: '🇺🇬', symbol: 'USh', name: 'Ugandan Shilling' },
  { currency_code: 'UYU', flag: '🇺🇾', symbol: '$U', name: 'Uruguayan Peso' },
  { currency_code: 'UZS', flag: '🇺🇿', symbol: 'лв', name: 'Uzbekistani Som' },
  { currency_code: 'VEF', flag: '🇻🇪', symbol: 'Bs', name: 'Venezuelan Bolívar' },
  { currency_code: 'VND', flag: '🇻🇳', symbol: '₫', name: 'Vietnamese Dong' },
  { currency_code: 'VUV', flag: '🇻🇺', symbol: 'VT', name: 'Vanuatu Vatu' },
  { currency_code: 'WST', flag: '🇼🇸', symbol: 'WS$', name: 'Samoan Tala' },
  { currency_code: 'XAF', flag: '🇨🇫', symbol: 'FCFA', name: 'Central African CFA Franc' },
  { currency_code: 'XCD', flag: '🇧🇲', symbol: 'EC$', name: 'East Caribbean Dollar' },
  { currency_code: 'XOF', flag: '🇧🇫', symbol: 'CFA', name: 'West African CFA Franc' },
  { currency_code: 'XPF', flag: '🇵🇫', symbol: '₣', name: 'CFP Franc' },
  { currency_code: 'YER', flag: '🇾🇪', symbol: '﷼', name: 'Yemeni Rial' },
  { currency_code: 'ZAR', flag: '🇿🇦', symbol: 'R', name: 'South African Rand' },
  { currency_code: 'ZMK', flag: '🇿🇲', symbol: 'ZK', name: 'Zambian Kwacha' },
];

// Helper function to get currency data by code
export const getCurrencyData = (currencyCode) => {
  return currencyData.find(currency => currency.currency_code === currencyCode);
};

// Helper function to get currency symbol by code
export const getCurrencySymbol = (currencyCode) => {
  const currency = getCurrencyData(currencyCode);
  return currency ? currency.symbol : '$';
};

// Helper function to get currency name by code
export const getCurrencyName = (currencyCode) => {
  const currency = getCurrencyData(currencyCode);
  return currency ? currency.name : 'US Dollar';
};

export const currencyOptions = () => {
  return currencyData.map((x) => {
    return {
      value: x.currency_code,
      label: x.flag + ' ' + x.symbol + ' (' + x.name + ')',
      symbol: x.symbol,
      name: x.name,
    };
  });
};
